"""Add cascade delete on foreign key

Revision ID: bdaff9426546
Revises: 2a6499b84ef5
Create Date: 2024-12-26 17:14:16.487165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bdaff9426546'
down_revision: Union[str, None] = '2a6499b84ef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('timestamp', sa.TIMESTAMP(), nullable=True))
    op.drop_constraint('attendance_roster_shift_id_fkey', 'attendance', type_='foreignkey')
    op.create_foreign_key("attendance_roster_shift_id_fkey", 'attendance', 'roster_shifts', ['roster_shift_id'], ['id'], ondelete='CASCADE')
    op.drop_column('attendance', 'checkout_time')
    op.drop_column('attendance', 'checkin_time')
    op.drop_constraint('roster_member_off_days_roster_member_id_fkey', 'roster_member_off_days', type_='foreignkey')
    op.create_foreign_key("roster_member_off_days_roster_member_id_fkey", 'roster_member_off_days', 'roster_members', ['roster_member_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('roster_shifts_roster_member_id_fkey', 'roster_shifts', type_='foreignkey')
    op.create_foreign_key("roster_shifts_roster_member_id_fkey", 'roster_shifts', 'roster_members', ['roster_member_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('rosters_manager_id_fkey', 'rosters', type_='foreignkey')
    op.create_foreign_key("rosters_manager_id_fkey", 'rosters', 'users', ['manager_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("rosters_manager_id_fkey", 'rosters', type_='foreignkey')
    op.create_foreign_key('rosters_manager_id_fkey', 'rosters', 'users', ['manager_id'], ['id'])
    op.drop_constraint("roster_shifts_roster_member_id_fkey", 'roster_shifts', type_='foreignkey')
    op.create_foreign_key('roster_shifts_roster_member_id_fkey', 'roster_shifts', 'roster_members', ['roster_member_id'], ['id'])
    op.drop_constraint("roster_member_off_days_roster_member_id_fkey", 'roster_member_off_days', type_='foreignkey')
    op.create_foreign_key('roster_member_off_days_roster_member_id_fkey', 'roster_member_off_days', 'roster_members', ['roster_member_id'], ['id'])
    op.add_column('attendance', sa.Column('checkin_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('attendance', sa.Column('checkout_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint("attendance_roster_shift_id_fkey", 'attendance', type_='foreignkey')
    op.create_foreign_key('attendance_roster_shift_id_fkey', 'attendance', 'roster_shifts', ['roster_shift_id'], ['id'])
    op.drop_column('attendance', 'timestamp')
    # ### end Alembic commands ###
